# Here we learn how to catch error or error handaling in python
# In our above code the shows NameError
print(y) # To run below code plz comment this 
# Now use try catch statement 
try:
    print(y)
except:
    print("Error Occured") 
print("Moving On...")       